// CircleChat 原生客户端 — 国际化（zh / en / ja）

enum AppLang { zh, en, ja }

typedef Strings = Map<String, String>;

class I18n {
  final AppLang lang;
  final Strings strings;

  I18n(this.lang, this.strings);

  String tr(String key, {List<String> args = const []}) {
    var s = strings[key] ?? key;
    for (var i = 0; i < args.length; i++) {
      s = s.replaceAll('{$i}', args[i]);
    }
    // 兼容服务端直接下发的英文 / 中文原文：键若为空则原样返回
    return s;
  }

  bool get isZh => lang == AppLang.zh;

  static const zh = <String, String>{
    'app.name': 'CircleChat',
    // 登录
    'login.site': '站点地址',
    'login.siteHint': '例如 https://chat.example.com',
    'login.connect': '连接站点',
    'login.username': '用户名',
    'login.password': '密码',
    'login.submit': '登录',
    'login.register': '注册',
    'login.twofa': '两步验证',
    'login.twofa.code': '验证码',
    'login.pending': '账号待管理员审核',
    'login.rejected': '账号已被拒绝',
    'login.banned': '账号已被封禁',
    'login.ipBanned': 'IP 已被封禁',
    'login.rateLimited': '尝试次数过多，请稍后再试',
    'login.badCredentials': '用户名或密码错误',
    'login.forceChange': '首次登录请修改密码',
    'login.curPass': '当前密码',
    'login.newPass': '新密码',
    'login.confirm': '确认',
    'login.email': '邮箱（可选）',
    'login.back': '返回登录',
    'login.registerSubmit': '提交注册',
    'login.siteDisclaimer': '输入你自己的 CircleChat 站点地址以连接。\n客户端通过调用该站点的 API 工作，数据由该站点托管。',
    'login.siteInvalid': '站点地址无效',
    'site.invalid': '站点地址无效，请检查是否有误',
    'site.unreachable': '无法连接该站点，请检查地址与网络',
    'site.network': '网络错误，请稍后再试',
    'reg.fail': '注册失败',
    'reg.pendingHint': '注册申请已提交，等待管理员审核通过后即可登录。',
    // 侧栏 / 会话
    'chat.groups': '群组',
    'chat.dms': '私聊',
    'chat.friends': '好友',
    'chat.online': '在线',
    'chat.away': '离开',
    'chat.offline': '离线',
    'chat.typePlaceholder': '输入消息…',
    'chat.typing': '{0} 正在输入…',
    'chat.connected': '已连接',
    'chat.connecting': '连接中…',
    'chat.disconnected': '未连接',
    'chat.placeholder': '选择左侧会话，开始聊天',
    // 消息操作
    'chat.copy': '复制',
    'chat.recall': '撤回',
    'chat.report': '举报',
    'chat.forward': '转发',
    'chat.react': '回应',
    'chat.reply': '回复',
    'chat.recalled': '消息已撤回',
    // 上传
    'chat.upload.tooBig': '{0} 超过 {1} 上限',
    'chat.upload.failed': '上传失败',
    'chat.upload.retry': '请重试',
    'chat.dm.gateToast': '私聊消息仅好友可见，无法引用或发送文件',
    // 通知 / 邮箱
    'mailbox.title': '消息中心',
    'mailbox.announcements': '公告',
    'mailbox.notifications': '通知',
    'mailbox.penalties': '处罚',
    'mailbox.empty': '暂无内容',
    // 通用
    'common.ok': '确定',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.opFailed': '操作失败',
    'common.opFailedRetry': '操作失败，请重试',
    'common.loading': '加载中…',
    'common.empty': '暂无数据',
    // 侧栏 / 会话操作
    'common.me': '我',
    'common.logout': '退出登录',
    'sidebar.search.placeholder': '搜索群组或好友',
    'nav.collapse': '折叠导航栏',
    'nav.expand': '展开导航栏',
    'chat.group.create': '创建群组',
    'chat.group.join': '加入群组',
    'chat.group.create.name': '群组名称',
    'chat.group.join.gid': '群组 ID',
    'chat.friend.add': '添加好友',
    'chat.friend.add.name': '对方用户名',
    'chat.friend.accept': '同意',
    'chat.friend.reject': '拒绝',
    'chat.friend.empty': '暂无群组或好友',
    'chat.report.title': '举报消息',
    'chat.report.reason': '举报原因',
    'chat.report.submit': '提交举报',
    'chat.report.done': '举报已提交',
    'chat.report.fail': '举报失败，请重试',
    'chat.muted': '你已被禁言，无法发送消息',
    'chat.merge.label': '合并转发',
    'chat.create.done': '群组创建成功',
    'chat.create.fail': '创建失败',
    'chat.join.done': '已发送入群申请',
    'chat.join.fail': '操作失败',
    'chat.friend.done': '已发送好友申请',
    'chat.friend.fail': '申请失败',
    'chat.file.defaultName': '未命名文件',
    'site.notChat': '该地址不是 CircleChat 站点，请检查后重试',
  };

  static const en = <String, String>{
    'app.name': 'CircleChat',
    'login.site': 'Server address',
    'login.siteHint': 'e.g. https://chat.example.com',
    'login.connect': 'Connect',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Sign in',
    'login.register': 'Register',
    'login.twofa': 'Two-factor auth',
    'login.twofa.code': 'Code',
    'login.pending': 'Account pending admin review',
    'login.rejected': 'Account rejected',
    'login.banned': 'Account banned',
    'login.ipBanned': 'IP banned',
    'login.rateLimited': 'Too many attempts, try later',
    'login.badCredentials': 'Incorrect username or password',
    'login.forceChange': 'Please change password on first login',
    'login.curPass': 'Current password',
    'login.newPass': 'New password',
    'login.confirm': 'Confirm',
    'login.email': 'Email (optional)',
    'login.back': 'Back to login',
    'login.registerSubmit': 'Submit registration',
    'login.siteDisclaimer': 'Enter your own CircleChat server address to connect.\nThe client works by calling your server API; data is hosted by that server.',
    'login.siteInvalid': 'Invalid server address',
    'site.invalid': 'Invalid server address',
    'site.unreachable': 'Cannot reach the server. Check address and network.',
    'site.network': 'Network error, try again later',
    'reg.fail': 'Registration failed',
    'reg.pendingHint': 'Registration submitted. It will be active after admin approval.',
    'chat.groups': 'Groups',
    'chat.dms': 'Direct messages',
    'chat.friends': 'Friends',
    'chat.online': 'Online',
    'chat.away': 'Away',
    'chat.offline': 'Offline',
    'chat.typePlaceholder': 'Type a message…',
    'chat.typing': '{0} is typing…',
    'chat.connected': 'Connected',
    'chat.connecting': 'Connecting…',
    'chat.disconnected': 'Disconnected',
    'chat.placeholder': 'Select a conversation to start chatting',
    'chat.copy': 'Copy',
    'chat.recall': 'Recall',
    'chat.report': 'Report',
    'chat.forward': 'Forward',
    'chat.react': 'React',
    'chat.reply': 'Reply',
    'chat.recalled': 'Message recalled',
    'chat.upload.tooBig': '{0} exceeds {1} limit',
    'chat.upload.failed': 'Upload failed',
    'chat.upload.retry': 'Please retry',
    'chat.dm.gateToast': 'DM is friends-only; replies and files are disabled',
    'mailbox.title': 'Inbox',
    'mailbox.announcements': 'Announcements',
    'mailbox.notifications': 'Notifications',
    'mailbox.penalties': 'Penalties',
    'mailbox.empty': 'Nothing here',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.opFailed': 'Operation failed',
    'common.opFailedRetry': 'Operation failed, retry',
    'common.loading': 'Loading…',
    'common.empty': 'Nothing yet',
    'common.me': 'me',
    'common.logout': 'Log out',
    'sidebar.search.placeholder': 'Search groups or friends',
    'nav.collapse': 'Collapse navigation',
    'nav.expand': 'Expand navigation',
    'chat.group.create': 'Create group',
    'chat.group.join': 'Join group',
    'chat.group.create.name': 'Group name',
    'chat.group.join.gid': 'Group ID',
    'chat.friend.add': 'Add friend',
    'chat.friend.add.name': 'Username',
    'chat.friend.accept': 'Accept',
    'chat.friend.reject': 'Decline',
    'chat.friend.empty': 'No groups or friends yet',
    'chat.report.title': 'Report message',
    'chat.report.reason': 'Reason',
    'chat.report.submit': 'Submit report',
    'chat.report.done': 'Report submitted',
    'chat.report.fail': 'Report failed, please retry',
    'chat.muted': 'You are muted and cannot send messages',
    'chat.merge.label': 'Merge forward',
    'chat.create.done': 'Group created',
    'chat.create.fail': 'Creation failed',
    'chat.join.done': 'Join request sent',
    'chat.join.fail': 'Operation failed',
    'chat.friend.done': 'Friend request sent',
    'chat.friend.fail': 'Request failed',
    'chat.file.defaultName': 'Untitled file',
    'site.notChat': 'This address is not a CircleChat site, please check it',
  };

  static const ja = <String, String>{
    'app.name': 'CircleChat',
    'login.site': 'サイトアドレス',
    'login.siteHint': '例: https://chat.example.com',
    'login.connect': '接続',
    'login.username': 'ユーザー名',
    'login.password': 'パスワード',
    'login.submit': 'ログイン',
    'login.register': '登録',
    'login.twofa': '二段階認証',
    'login.twofa.code': '認証コード',
    'login.pending': '管理者の承認待ちです',
    'login.rejected': 'アカウントが拒否されました',
    'login.banned': 'アカウントは停止されています',
    'login.ipBanned': 'IP が停止されています',
    'login.rateLimited': '試行回数が多すぎます。後でお試しください',
    'login.badCredentials': 'ユーザー名またはパスワードが違います',
    'login.forceChange': '初回ログインのためパスワード変更が必要です',
    'login.curPass': '現在のパスワード',
    'login.newPass': '新しいパスワード',
    'login.confirm': '確認',
    'login.email': 'メール（任意）',
    'login.back': 'ログインに戻る',
    'login.registerSubmit': '登録を送信',
    'login.siteDisclaimer': '接続先の CircleChat サーバーアドレスを入力してください。\nクライアントはそのサーバーの API を呼び出して動作し、データはそのサーバーが管理します。',
    'login.siteInvalid': 'サーバーアドレスが無効です',
    'site.invalid': 'サーバーアドレスが無効です',
    'site.unreachable': 'サーバーに接続できません。アドレスとネットワークを確認してください',
    'site.network': 'ネットワークエラー。後でお試しください',
    'reg.fail': '登録に失敗しました',
    'reg.pendingHint': '登録申請を送信しました。管理者の承認後にログイン可能になります。',
    'chat.groups': 'グループ',
    'chat.dms': 'ダイレクトメッセージ',
    'chat.friends': 'フレンド',
    'chat.online': 'オンライン',
    'chat.away': '離席中',
    'chat.offline': 'オフライン',
    'chat.typePlaceholder': 'メッセージを入力…',
    'chat.typing': '{0} が入力中…',
    'chat.connected': '接続済み',
    'chat.connecting': '接続中…',
    'chat.disconnected': '未接続',
    'chat.placeholder': '左の会話を選択してチャットを開始',
    'chat.copy': 'コピー',
    'chat.recall': '取り消し',
    'chat.report': '通報',
    'chat.forward': '転送',
    'chat.react': 'リアクション',
    'chat.reply': '返信',
    'chat.recalled': 'メッセージは取り消されました',
    'chat.upload.tooBig': '{0} が {1} の上限を超えています',
    'chat.upload.failed': 'アップロード失敗',
    'chat.upload.retry': '再試行してください',
    'chat.dm.gateToast': 'DM はフレンド限定のため、返信・ファイル送信はできません',
    'mailbox.title': 'インボックス',
    'mailbox.announcements': 'お知らせ',
    'mailbox.notifications': '通知',
    'mailbox.penalties': '処罰',
    'mailbox.empty': 'コンテンツはありません',
    'common.ok': 'OK',
    'common.cancel': 'キャンセル',
    'common.close': '閉じる',
    'common.opFailed': '操作に失敗しました',
    'common.opFailedRetry': '操作に失敗しました。再試行してください',
    'common.loading': '読み込み中…',
    'common.empty': 'データはありません',
    'common.me': '自分',
    'common.logout': 'ログアウト',
    'sidebar.search.placeholder': 'グループやフレンドを検索',
    'nav.collapse': 'ナビゲーションを折りたたむ',
    'nav.expand': 'ナビゲーションを展開',
    'chat.group.create': 'グループ作成',
    'chat.group.join': 'グループに参加',
    'chat.group.create.name': 'グループ名',
    'chat.group.join.gid': 'グループ ID',
    'chat.friend.add': 'フレンド追加',
    'chat.friend.add.name': 'ユーザー名',
    'chat.friend.accept': '承認',
    'chat.friend.reject': '拒否',
    'chat.friend.empty': 'グループやフレンドはありません',
    'chat.report.title': 'メッセージを通報',
    'chat.report.reason': '通報理由',
    'chat.report.submit': '送信',
    'chat.report.done': '通報を送信しました',
    'chat.report.fail': '通報に失敗しました。再試行してください',
    'chat.muted': 'ミュート中のため送信できません',
    'chat.merge.label': 'まとめ転送',
    'chat.create.done': 'グループを作成しました',
    'chat.create.fail': '作成に失敗しました',
    'chat.join.done': '参加申請を送信しました',
    'chat.join.fail': '操作に失敗しました',
    'chat.friend.done': 'フレンド申請を送信しました',
    'chat.friend.fail': '申請に失敗しました',
    'chat.file.defaultName': '無題のファイル',
    'site.notChat': 'このアドレスは CircleChat サイトではありません。確認してください',
  };

  static I18n of(AppLang lang) {
    switch (lang) {
      case AppLang.zh:
        return I18n(lang, zh);
      case AppLang.en:
        return I18n(lang, en);
      case AppLang.ja:
        return I18n(lang, ja);
    }
  }

  /// 从平台语言检测默认语言。
  static AppLang fromPlatform() {
    // 这里默认中文界面环境；后续可接入系统 locale。
    return AppLang.zh;
  }
}

/// 全局当前语言（运行时可变）。应用启动时初始化。
AppLang currentLang = AppLang.zh;

/// 获取当前语言的字符串表。
I18n get i18n => I18n.of(currentLang);

/// 便捷翻译函数。
String tr(String key, {List<String> args = const []}) => i18n.tr(key, args: args);